name: cocaapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  qr_mobile_vision: ^0.3.1
  flare_flutter: ^2.0.1
  firebase_core: ^0.4.1+3
  firebase_auth: 0.15.5+2
  pin_code_fields: 3.0.0
  cupertino_icons: ^0.1.3
  bottom_navy_bar: ^5.4.0
  sliding_up_panel: ^1.0.2
  carousel_slider: ^2.1.0
  modal_bottom_sheet: ^0.1.6+1
  animate_do:
  scoped_model:
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  hex: ^0.1.2






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/flare/
    - assets/images/
  fonts:
    - family: CocaCola
      fonts:
        - asset: assets/fonts/Coca-Cola.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

